/**
@file solver.h
The functions in this module do the same thing as in solver1.h except 
that in this part the minesweeper game is generated by the application
and therefore there is no screenInteraction image Recognition part 
involved. Only used in TerminalVersion. Please refer to solver1.h
for explanations of functions.
*/
#ifndef _SOLVER_H
#define _SOLVER_H

#include "logic.h"
#include "field.h"


void solver(field * f);

void solver_single(field * f);

void solver_pair(field *f);

void solver_pair_special(field *f);


#endif


